### ISSUE TITLE
I am getting errors while syncdb

### ISSUE THREAD

**Issue by KakarN** [jbittel/django-multimedia#5]
Hello,
While syncdb I am getting this error:

CommandError: System check identified some issues:

ERRORS:
multimedia.Video.thumbnail_image: (fields.E300) Field defines a relation with model 'Image', which is either not installed, or is abstract.

What can be the problem? I would really be grateful if you could help me.

Thank you.

**Comment by jbittel** [comment]
I believe the issue is that you don't have django-filer installed. Although the project does not currently use it, the migrations still refer to filer fields from past migrations, so they expect it to be installed.

**Comment by LuizPeroso** [comment]
I'm having the same problem and i have de package installed.

**Comment by jbittel** [comment]
Try disabling South migrations for the project to work around this by adding this to your settings file:

    SOUTH_MIGRATION_MODULES = {
        'multimedia': 'ignore',
    }

That invalid path with cause South to not try to migrate the app, and instead you can just use syncdb to install all of the required tables. Once the tables are created, you can remove this block. The South migration history is likely going to need to go away anyway, as there's been so many changes to the app.
